// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nIAkPd5U8mt9WKC8D0FNzacGs8_5z64',
    appId: '1:822362109936:web:3925715ab2fe55f75e0f35',
    messagingSenderId: '822362109936',
    projectId: 'names-app-1c5b7',
    authDomain: 'names-app-1c5b7.firebaseapp.com',
    storageBucket: 'names-app-1c5b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzw-7w6DFnamWpt-EJc5N_OjswKpRGiA8',
    appId: '1:822362109936:android:05cbb869450191115e0f35',
    messagingSenderId: '822362109936',
    projectId: 'names-app-1c5b7',
    storageBucket: 'names-app-1c5b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaN-LSg_bXVgZqxxdNRD3cxam9VwoN9Uo',
    appId: '1:822362109936:ios:f22e3394f534e1d45e0f35',
    messagingSenderId: '822362109936',
    projectId: 'names-app-1c5b7',
    storageBucket: 'names-app-1c5b7.firebasestorage.app',
    iosBundleId: 'com.example.namesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaN-LSg_bXVgZqxxdNRD3cxam9VwoN9Uo',
    appId: '1:822362109936:ios:f22e3394f534e1d45e0f35',
    messagingSenderId: '822362109936',
    projectId: 'names-app-1c5b7',
    storageBucket: 'names-app-1c5b7.firebasestorage.app',
    iosBundleId: 'com.example.namesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0nIAkPd5U8mt9WKC8D0FNzacGs8_5z64',
    appId: '1:822362109936:web:81492ca681b2949a5e0f35',
    messagingSenderId: '822362109936',
    projectId: 'names-app-1c5b7',
    authDomain: 'names-app-1c5b7.firebaseapp.com',
    storageBucket: 'names-app-1c5b7.firebasestorage.app',
  );
}
